platform :ios, '13.0'

target 'eMoneySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project './eMoneySDK.xcodeproj'
  use_frameworks! :linkage => :static

  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
  pod 'Kingfisher', '~> 7.0'
  pod 'CryptoSwift', '~> 1.6.0'
  pod 'SwiftyTesseract', '~> 3.1.3'
  pod 'TensorFlowLiteSwift', '~> 2.7.0'
  pod 'PureLiveSDK', :git => 'https://gitlab.com/purelive/purelive-ios-sdk.git' , :tag => '6.4.0.1'
  pod 'SwiftMessages'
  pod 'FSPagerView'
  pod 'lottie-ios'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
 end
end

